version: '3.8'

services:
  api:
    container_name: api
    restart: on-failure

    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile

    command: ./api

    environment:
      - DB_NAME=${DB_NAME} 
      - HOST=${HOST}

    ports:
      - ${PORT}:${PORT}

